[package]
name = "nuclear-monitor"
version = "0.1.0"
edition = "2024"
description = "An animated nuclear reactor system monitor that visualizes system load"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
rand = "0.9.1"
ratatui = "0.29.0"
sysinfo = "0.34.2"
num_cpus = "1.16.0"
